# Generated by Django 3.1 on 2020-08-22 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='desc',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Descripcion'),
        ),
    ]
